"""
Django settings for roams_pro project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from logging.handlers import RotatingFileHandler
import environ




# --- Environment variables ---
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Initialize environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
DEBUG = env.bool("DEBUG", default=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'roams_api',
    "roams_opcua_mgr",
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # for TokenAuth
    'django_filters',
    'corsheaders',
      
]

 
      
CORS_ALLOW_ALL_ORIGINS = False  # default is False, be explicit Better security practice in production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
      'http://127.0.0.1:5173',  # React dev server
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'roams_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, "roams_pro/templates"),
                os.path.join(BASE_DIR, "roams_opcua_mgr/templates"),
                os.path.join(BASE_DIR, "roams_api/templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roams_pro.wsgi.application'
ASGI_APPLICATION = 'roams_pro.asgi.application'
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:5173"]



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


SECRET_KEY = env("SECRET_KEY", default="fallback-secret-key")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", default="127.0.0.1"),
        "PORT": env("DB_PORT", default="5432"),
        'CONN_MAX_AGE': 0,  # ✅ close connection after each request
        "OPTIONS": {
            "connect_timeout": 30,
        }
    }
}

# Optional: Redis cache

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://127.0.0.1:6379/0"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Ensure Redis is running
            
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# --- Static files ---

STATIC_URL = "/static/"

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, "roams_pro", "static"),
    os.path.join(BASE_DIR, "roams_opcua_mgr", "static"),
    ]  # app-level static files (dev use)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    # where collectstatic will put them

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Logs directory ---
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {  # ✅ added to match file_access
            "format": "{levelname} {message}",
            "style": "{",
        },
        "access": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "WARNING",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "debug.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "delay": True,
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_access": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "access.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "access",  # ✅ fixed mismatch
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file_debug", "file_error"],
        "level": "DEBUG",  # default, will be overridden below
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_debug", "file_error"],
            "level": "WARNING",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        "access_logger": {
            "handlers": ["file_access"],
            "level": "INFO",
            "propagate": False,
        },
        "django.utils.autoreload": {
            "handlers": [],
            "level": "CRITICAL",
            "propagate": False,
        },
    },
}

# ✅ Now safely override root level
LOGGING["root"]["level"] = "DEBUG" if DEBUG else "INFO"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"  # After login, go to the dashboard
LOGOUT_REDIRECT_URL = "/login/"  # After logout, redirect to login page
# ==================== THRESHOLD & ALERT CONFIGURATION ====================

# Email notifications for threshold breaches
THRESHOLD_EMAIL_ENABLED = env.bool('THRESHOLD_EMAIL_ENABLED', default=True)
THRESHOLD_EMAIL_FROM = env('THRESHOLD_EMAIL_FROM', default='alerts@roams.local')
THRESHOLD_CRITICAL_EMAILS = env.list('THRESHOLD_CRITICAL_EMAILS', default=[])
THRESHOLD_WARNING_EMAILS = env.list('THRESHOLD_WARNING_EMAILS', default=[])

# Email backend configuration
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

# SMS notifications via Twilio
THRESHOLD_SMS_ENABLED = env.bool('THRESHOLD_SMS_ENABLED', default=False)
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID', default=None)
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN', default=None)
TWILIO_PHONE_FROM = env('TWILIO_PHONE_FROM', default=None)
THRESHOLD_CRITICAL_PHONES = env.list('THRESHOLD_CRITICAL_PHONES', default=[])
THRESHOLD_WARNING_PHONES = env.list('THRESHOLD_WARNING_PHONES', default=[])