"""
Django settings for roams_pro project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from logging.handlers import RotatingFileHandler
import environ




# --- Environment variables ---
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Initialize environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
DEBUG = env.bool("DEBUG", default=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!


ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '144.91.79.167',  # Contabo VPS IP
    # Add your domain when you get SSL: 'roams.yourdomain.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # for TokenAuth
    'django_filters',
    'corsheaders',
    'channels',
    'roams_api',
    "roams_opcua_mgr",
]

 
      
CORS_ALLOW_ALL_ORIGINS = False  # default is False, be explicit Better security practice in production
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    'http://127.0.0.1:5173',  # React dev server
    'http://192.168.183.232:5173',  # WSL network access
    'http://192.168.183.232:8000',  # Direct backend access on WSL
    'http://192.168.1.100:5173',  # Windows Wi-Fi IP for phone access
    'http://192.168.1.100:8000',  # Windows backend access
    'http://144.91.79.167',  # Contabo VPS - Nginx port 80
    'http://144.91.79.167:3000',  # Contabo VPS - Frontend dev server
    'http://144.91.79.167:5173',  # Contabo VPS - Vite dev server
    'http://144.91.79.167:8000',  # Contabo VPS - Django direct access
]

# Allow credentials for CORS (if needed for cookies/sessions)
CORS_ALLOW_CREDENTIALS = False  # Set to True only if using session auth
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'roams_pro.middleware.AdminTimeoutMiddleware',  # Add timeout management for admin
]

# ==================== PRODUCTION SECURITY SETTINGS ====================
# SSL/HTTPS configuration (only enforced when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
    SESSION_COOKIE_SECURE = True  # Send session cookies only over HTTPS
    CSRF_COOKIE_SECURE = True  # Send CSRF cookies only over HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Trust NGINX proxy
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# Session security
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF token
CSRF_COOKIE_SAMESITE = 'Lax'

ROOT_URLCONF = 'roams_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                os.path.join(BASE_DIR, "roams_pro/templates"),
                os.path.join(BASE_DIR, "roams_opcua_mgr/templates"),
                os.path.join(BASE_DIR, "roams_api/templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'roams_pro.wsgi.application'
ASGI_APPLICATION = 'roams_pro.asgi.application'
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000", 
    "http://localhost:5173", 
    "http://127.0.0.1:5173",
    "http://192.168.183.232:5173",  # Local network frontend
    "http://192.168.183.232:8000",  # Local network backend
    'http://192.168.1.100:5173',  # Windows Wi-Fi IP for phone access
    'http://192.168.1.100:8000',  # Windows backend access
    'http://144.91.79.167',  # Contabo VPS - Frontend (Nginx port 80)
    'http://144.91.79.167:8000',  # Contabo VPS - Django direct access
]



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


SECRET_KEY = env.str("SECRET_KEY")


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DB_NAME", default="roams_db"),
        "USER": env.str("DB_USER", default="postgres"),
        "PASSWORD": env.str("DB_PASSWORD", default="password"),
        "HOST": env.str("DB_HOST", default="127.0.0.1"),
        "PORT": env.str("DB_PORT", default="5432"),
        'CONN_MAX_AGE': 600,  # 10-minute connection pooling (0 = no pooling, not recommended for production)
        "OPTIONS": {
            "connect_timeout": 30,
            # Increase statement timeout significantly (30 minutes) to prevent admin operations from timing out
            "options": "-c statement_timeout=1800000 -c lock_timeout=300000",
        }
    }
}

# Optional: Redis cache

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env.str("REDIS_URL", default="redis://127.0.0.1:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
        },
        "KEY_PREFIX": "roams",  # Namespace for cache keys
        "TIMEOUT": 300,  # Default cache timeout: 5 minutes
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

# API Rate Limiting (only in production to prevent abuse)
if not DEBUG:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ]
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'anon': '100/hour',  # Unauthenticated requests
        'user': '1000/hour',  # Authenticated requests
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kampala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# --- Static files ---

STATIC_URL = "/static/"

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, "roams_pro", "static"),
    os.path.join(BASE_DIR, "roams_opcua_mgr", "static"),
    ]  # app-level static files (dev use)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    # where collectstatic will put them

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Logs directory ---
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {  # ✅ added to match file_access
            "format": "{levelname} {message}",
            "style": "{",
        },
        "access": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO" if DEBUG else "WARNING",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "debug.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
            "delay": True,
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        "file_access": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "access.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "access",  # ✅ fixed mismatch
            "encoding": "utf-8",
        },
    },
    "root": {
        "handlers": ["console", "file_debug", "file_error"],
        "level": "DEBUG",  # default, will be overridden below
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_debug", "file_error"],
            "level": "WARNING",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        "access_logger": {
            "handlers": ["file_access"],
            "level": "INFO",
            "propagate": False,
        },
        "django.utils.autoreload": {
            "handlers": [],
            "level": "CRITICAL",
            "propagate": False,
        },
    },
}

# ✅ Now safely override root level
LOGGING["root"]["level"] = "DEBUG" if DEBUG else "INFO"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"  # After login, go to the dashboard
LOGOUT_REDIRECT_URL = "/login/"  # After logout, redirect to login page
# ==================== THRESHOLD & ALERT CONFIGURATION ====================

# Email notifications for threshold breaches
THRESHOLD_EMAIL_ENABLED = env.bool('THRESHOLD_EMAIL_ENABLED', default=True)
THRESHOLD_EMAIL_FROM = env.str('THRESHOLD_EMAIL_FROM', default='alerts@roams.local')
THRESHOLD_CRITICAL_EMAILS = env.list('THRESHOLD_CRITICAL_EMAILS', default=[])
THRESHOLD_WARNING_EMAILS = env.list('THRESHOLD_WARNING_EMAILS', default=[])

# Email backend configuration
EMAIL_BACKEND = env.str('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env.str('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', default='')

# SMS notifications via Twilio
THRESHOLD_SMS_ENABLED = env.bool('THRESHOLD_SMS_ENABLED', False)
TWILIO_ACCOUNT_SID = env.str('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env.str('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_FROM = env.str('TWILIO_PHONE_FROM', default='')
THRESHOLD_CRITICAL_PHONES = env.list('THRESHOLD_CRITICAL_PHONES', default=[])
THRESHOLD_WARNING_PHONES = env.list('THRESHOLD_WARNING_PHONES', default=[])

# ==================== DJANGO ADMIN & FORM LIMITS ====================
# Increase max number of form fields for admin with large datasets (e.g., 126K breaches)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # Default is 1000, increased for large datasets
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB