# Generated by Django 4.2.23 on 2025-09-04 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import roams_opcua_mgr.models.client_config_model
import roams_opcua_mgr.models.node_config_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anonymous', models.BooleanField(default=True, help_text='Allow anonymous connections. If checked, username and password fields will be disabled.')),
                ('username', models.CharField(blank=True, help_text='Enter the username for authentication. This field is ignored for anonymous connections.', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='Enter the password for authentication. This field is ignored for anonymous connections.', max_length=100, null=True, verbose_name='Password')),
            ],
            options={
                'verbose_name': 'Authentication Setting',
                'verbose_name_plural': 'Authentication Settings',
            },
        ),
        migrations.CreateModel(
            name='OpcUaClientConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(help_text='Name of the station.', max_length=100)),
                ('endpoint_url', models.CharField(help_text='Example: opc.tcp://kasmic.ddns.net:4840', max_length=2048, validators=[roams_opcua_mgr.models.client_config_model.validate_opcua_url], verbose_name='OPC UA Endpoint URL')),
                ('active', models.BooleanField(default=False, help_text='Indicates whether this configuration is active.')),
                ('last_connected', models.DateTimeField(blank=True, help_text='Timestamp of the last successful connection.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the configuration was created.')),
                ('connection_status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Faulty', 'Faulty')], default='Disconnected', max_length=20)),
                ('security_policy', models.CharField(choices=[('None', 'None'), ('Basic128Rsa15', 'Basic128Rsa15'), ('Basic256', 'Basic256'), ('Basic256sha256', 'Basic256sha256')], default='None', help_text='The security policy for the OPC UA client.', max_length=20, verbose_name='Security Policy')),
                ('security_mode', models.CharField(choices=[('None', 'None'), ('Sign', 'Sign'), ('Sign_and_Encrypt', 'Sign & Encrypt')], default='None', help_text='The security mode for message exchange.', max_length=20, verbose_name='Security Mode')),
                ('show_advanced_properties', models.BooleanField(default=False, help_text='Enable this to show advanced connection properties such as timeouts and intervals.')),
                ('session_time_out', models.IntegerField(default=30000, help_text='Session timeout in milliseconds (1000ms to 3600000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3600000)])),
                ('secure_time_out', models.IntegerField(default=10000, help_text='Secure timeout in milliseconds (1000ms to 30000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)])),
                ('connection_time_out', models.IntegerField(default=30000, help_text='Connection timeout in milliseconds (1000ms to 60000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(60000)])),
                ('request_time_out', models.IntegerField(default=10000, help_text='Request timeout in milliseconds (1000ms to 30000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)])),
                ('acknowledge_time_out', models.IntegerField(default=5000, help_text='Acknowledge timeout in milliseconds (1000ms to 10000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)])),
                ('subscription_interval', models.IntegerField(default=5000, help_text='Subscription interval in milliseconds (1000ms to 60000ms).', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(60000)])),
            ],
            options={
                'verbose_name': 'OPC UA Client Configuration',
                'verbose_name_plural': 'OPC UA Client Configurations',
            },
        ),
        migrations.CreateModel(
            name='OPCUANode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_new_tag_name', models.CharField(blank=True, default='', help_text='Enter a new tag name (if not already in the list).', max_length=255)),
                ('tag_units', models.CharField(blank=True, default='', help_text="Engineering units for the tag (e.g., 'm³/h', 'm³',°C, bars etc.).", max_length=50, null=True)),
                ('access_level', models.CharField(choices=[('Read_only', '🔒Read Only'), ('Write_only', '✍️Write Only'), ('Read_write', '🔓Read/Write')], default='Read_only', help_text='Specify the access level of the tag.', max_length=10)),
                ('node_id', models.CharField(help_text="Enter the Node ID in the format 'ns=<number>;i=<number>'.", max_length=255, validators=[roams_opcua_mgr.models.node_config_model.validate_node_id])),
                ('last_value', models.CharField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client_config', models.ForeignKey(help_text='Link to the OPC UA client configuration.', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuaclientconfig')),
            ],
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name for OPC UA Node configuration.', max_length=255, unique=True)),
                ('tag_units', models.CharField(blank=True, default='', help_text='Engineering units (e.g., m³/h, °C, bars,m³ etc.).', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcUaWriteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('command', models.CharField(blank=True, help_text='Optional command like STOP or START', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('client_config', models.ForeignKey(help_text='Client that performed the write', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuaclientconfig')),
                ('node', models.ForeignKey(help_text='The node that was written to', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuanode')),
            ],
        ),
        migrations.CreateModel(
            name='OpcUaReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('client_config', models.ForeignKey(help_text='Client that performed the read', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuaclientconfig')),
                ('node', models.ForeignKey(help_text='The node that was read', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuanode')),
            ],
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='tag_name',
            field=models.ForeignKey(blank=True, help_text='Choose from predefined tags or add a custom tag.', null=True, on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.tagname'),
        ),
        migrations.AddConstraint(
            model_name='opcuaclientconfig',
            constraint=models.UniqueConstraint(fields=('station_name', 'endpoint_url'), name='unique_station_name_endpoint_per_client'),
        ),
        migrations.AddField(
            model_name='authenticationsetting',
            name='client_config',
            field=models.OneToOneField(help_text='Link to the OPCUA Client Configuration.', on_delete=django.db.models.deletion.CASCADE, to='roams_opcua_mgr.opcuaclientconfig'),
        ),
        migrations.AddIndex(
            model_name='opcuanode',
            index=models.Index(fields=['node_id'], name='roams_opcua_node_id_1501f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='opcuanode',
            constraint=models.UniqueConstraint(fields=('client_config', 'node_id'), name='unique_node_id_per_client'),
        ),
        migrations.AddConstraint(
            model_name='opcuanode',
            constraint=models.UniqueConstraint(fields=('client_config', 'tag_name'), name='unique_tag_per_client'),
        ),
    ]
