# Generated by Django 4.2.23 on 2025-09-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcuanode',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Maximum value for the tag (numeric)', null=True),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Minimum value for the tag (numeric)', null=True),
        ),
    ]
