# Generated by Django 5.2.7 on 2025-10-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0002_opcuanode_max_value_opcuanode_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcuanode',
            name='is_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
