# Generated by Django 5.2.7 on 2025-10-20 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0005_connectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcuaclientconfig',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the station.', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='opcuaclientconfig',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the station.', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
