# Generated by Django 5.2.7 on 2025-12-21 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0006_opcuaclientconfig_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum acceptable value', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Maximum acceptable value', null=True)),
                ('warning_level', models.FloatField(blank=True, help_text='Value at which a warning is triggered', null=True)),
                ('critical_level', models.FloatField(blank=True, help_text='Value at which a critical alert is triggered', null=True)),
                ('severity', models.CharField(choices=[('Warning', 'Warning'), ('Critical', 'Critical')], default='Warning', help_text='Default severity level for breaches', max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Whether this threshold is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(help_text='The OPC UA node this threshold applies to', on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='roams_opcua_mgr.opcuanode')),
            ],
            options={
                'db_table': 'roams_opcua_mgr_tag_threshold',
            },
        ),
        migrations.CreateModel(
            name='ThresholdBreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='The value that triggered the breach')),
                ('level', models.CharField(choices=[('Warning', 'Warning'), ('Critical', 'Critical')], help_text='Whether this was a warning or critical breach', max_length=10)),
                ('acknowledged', models.BooleanField(default=False, help_text='Whether an operator has acknowledged this breach')),
                ('acknowledged_by', models.CharField(blank=True, help_text='Username of who acknowledged this breach', max_length=255, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When this breach was acknowledged', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the breach occurred')),
                ('node', models.ForeignKey(help_text='The node that breached', on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='roams_opcua_mgr.opcuanode')),
                ('threshold', models.ForeignKey(help_text='The threshold that was breached', on_delete=django.db.models.deletion.CASCADE, related_name='breach_events', to='roams_opcua_mgr.tagthreshold')),
            ],
            options={
                'db_table': 'roams_opcua_mgr_threshold_breach',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='tagthreshold',
            index=models.Index(fields=['node', 'active'], name='roams_opcua_node_id_bfd79c_idx'),
        ),
        migrations.AddIndex(
            model_name='tagthreshold',
            index=models.Index(fields=['updated_at'], name='roams_opcua_updated_428af8_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['node', 'timestamp'], name='roams_opcua_node_id_ca857b_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['threshold', 'timestamp'], name='roams_opcua_thresho_32b1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['level', 'acknowledged', 'timestamp'], name='roams_opcua_level_6cb250_idx'),
        ),
        migrations.AddIndex(
            model_name='thresholdbreach',
            index=models.Index(fields=['timestamp'], name='roams_opcua_timesta_978cb1_idx'),
        ),
    ]
