# Generated by Django 5.2.7 on 2025-12-22 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0008_consolidate_threshold_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('warning', 'Warning Only'), ('critical', 'Critical Only'), ('both', 'Both Warning & Critical')], default='both', help_text='Which alert levels should trigger notifications for this user', max_length=10)),
                ('email_enabled', models.BooleanField(default=True, help_text='Send email notifications to this user')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Send SMS notifications to this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Recipient',
                'verbose_name_plural': 'Notification Recipients',
                'ordering': ['node', 'user'],
            },
        ),
        migrations.RemoveIndex(
            model_name='thresholdbreach',
            name='roams_opcua_thresho_32b1ed_idx',
        ),
        migrations.RemoveIndex(
            model_name='thresholdbreach',
            name='roams_opcua_node_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='thresholdbreach',
            name='roams_opcua_level_ack_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='thresholdbreach',
            name='roams_opcua_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='opcuanode',
            new_name='roams_opcua_thresho_e34ac0_idx',
            old_name='roams_opcua_threshold_updated_idx',
        ),
        migrations.AlterField(
            model_name='opcuanode',
            name='max_value',
            field=models.FloatField(blank=True, help_text='Maximum acceptable value', null=True),
        ),
        migrations.AlterField(
            model_name='opcuanode',
            name='min_value',
            field=models.FloatField(blank=True, help_text='Minimum acceptable value', null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='node',
            field=models.ForeignKey(help_text='OPC UA node that triggers notifications', on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='roams_opcua_mgr.opcuanode'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(help_text='User who will receive notifications', on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together={('node', 'user')},
        ),
    ]
