# Generated by Django 5.2.7 on 2025-12-26 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0009_notificationrecipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecipient',
            name='alert_level',
            field=models.CharField(choices=[('warning', 'Warning Only'), ('critical', 'Critical Only'), ('both', 'Both Warning & Critical')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to='roams_opcua_mgr.opcuanode'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
