# Generated by Django 5.2.7 on 2025-12-27 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0010_alter_notificationrecipient_alert_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_log_retention_days', models.IntegerField(default=90, help_text='Delete alarm logs older than this many days (7-365)', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)])),
                ('breach_retention_days', models.IntegerField(default=90, help_text='Delete acknowledged threshold breaches older than this many days (7-365)', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)])),
                ('keep_unacknowledged', models.BooleanField(default=True, help_text='If True, never delete unacknowledged threshold breaches')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Enable automatic deletion of old records')),
                ('last_cleanup_at', models.DateTimeField(blank=True, help_text='When the last cleanup job ran', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alarm Retention Policy',
                'verbose_name_plural': 'Alarm Retention Policies',
            },
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='last_whole_number',
            field=models.IntegerField(blank=True, help_text='Last recorded whole number value for change detection', null=True),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='sample_on_whole_number_change',
            field=models.BooleanField(default=True, help_text='Only log data when whole number part changes (e.g., 47.6 -> 48)'),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='sampling_interval',
            field=models.IntegerField(default=60, help_text='Sampling interval in seconds (e.g., 60 for standard 1-minute intervals)'),
        ),
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_notified_at', models.DateTimeField(auto_now_add=True, help_text='When the first notification was sent')),
                ('last_notified_at', models.DateTimeField(help_text='When the last notification was sent')),
                ('interval', models.CharField(choices=[('15min', '15 Minutes'), ('30min', '30 Minutes'), ('1hour', '1 Hour'), ('4hours', '4 Hours'), ('daily', 'Daily'), ('never', 'Never')], default='1hour', help_text='How often to send notifications while breach is active', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether notifications are still being sent')),
                ('notification_count', models.IntegerField(default=1, help_text='How many times this breach has been notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breach', models.OneToOneField(help_text='The threshold breach this schedule is for', on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedule', to='roams_opcua_mgr.thresholdbreach')),
            ],
            options={
                'verbose_name': 'Notification Schedule',
                'verbose_name_plural': 'Notification Schedules',
            },
        ),
    ]
