# Generated by Django 6.0 on 2026-02-25 20:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_opcua_mgr', '0013_alter_authenticationsetting_client_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDeviceSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_power_rating', models.FloatField(blank=True, help_text='Motor power rating in kW. From device nameplate.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Motor Power Rating (kW)')),
                ('rated_current', models.FloatField(blank=True, help_text='Rated motor current in Amperes (A). From device nameplate.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rated Current (A)')),
                ('rated_flow_rate', models.FloatField(blank=True, help_text='Pump rated flow rate in m³/h (cubic meters per hour). From device nameplate.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rated Flow Rate (m³/h)')),
                ('rated_head', models.FloatField(blank=True, help_text='Pump rated head in meters (m). From device nameplate.', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rated Head (m)')),
                ('rated_pressure_bar', models.FloatField(blank=True, help_text='Pump rated pressure in bar. If using this instead of head, it will be converted (1 bar = 10.197 m head).', null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Rated Pressure (Bar)')),
                ('device_model', models.CharField(blank=True, help_text='Motor/pump model number from nameplate', max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Device manufacturer name', max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Device serial number', max_length=255, null=True)),
                ('installation_date', models.DateField(blank=True, help_text='When the device was installed', null=True)),
                ('last_maintenance', models.DateField(blank=True, help_text='Date of last maintenance', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the device or performance expectations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Station Device Specifications',
                'verbose_name_plural': 'Station Device Specifications',
            },
        ),
        migrations.RenameIndex(
            model_name='controlpermission',
            new_name='roams_opcua_user_id_b2a34a_idx',
            old_name='roams_opcua_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='controlpermission',
            new_name='roams_opcua_control_01a390_idx',
            old_name='roams_opcua_control_state_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstate',
            new_name='roams_opcua_node_id_43266d_idx',
            old_name='roams_opcua_node_id_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstate',
            new_name='roams_opcua_tag_typ_601c29_idx',
            old_name='roams_opcua_tag_type_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstate',
            new_name='roams_opcua_last_ch_5cb217_idx',
            old_name='roams_opcua_last_changed_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstatehistory',
            new_name='roams_opcua_control_7f039e_idx',
            old_name='roams_opcua_control_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstatehistory',
            new_name='roams_opcua_request_0c66c0_idx',
            old_name='roams_opcua_requester_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstatehistory',
            new_name='roams_opcua_change__239f06_idx',
            old_name='roams_opcua_change_type_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstaterequest',
            new_name='roams_opcua_status_b4dd5b_idx',
            old_name='roams_opcua_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='controlstaterequest',
            new_name='roams_opcua_control_3fccda_idx',
            old_name='roams_opcua_control_status_idx',
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='data_type',
            field=models.CharField(choices=[('Float', 'Float (32-bit)'), ('Double', 'Double (64-bit)'), ('Int16', 'Int16 (Signed 16-bit)'), ('UInt16', 'UInt16 (Unsigned 16-bit)'), ('Int32', 'Int32 (Signed 32-bit)'), ('UInt32', 'UInt32 (Unsigned 32-bit)'), ('Boolean', 'Boolean (True/False)'), ('String', 'String')], default='Float', help_text='OPC UA node data type', max_length=20),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='decimal_places',
            field=models.IntegerField(default=2, help_text='Number of decimal places to display (0 for integers)'),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='display_max',
            field=models.FloatField(blank=True, help_text='Maximum value for gauge/chart display (auto-scale if blank)', null=True),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='display_min',
            field=models.FloatField(blank=True, help_text='Minimum value for gauge/chart display (auto-scale if blank)', null=True),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='display_type',
            field=models.CharField(choices=[('numeric', '📊 Numeric Display'), ('gauge', '🎯 Gauge (Linear)'), ('gauge-circular', '🎡 Gauge (Circular)'), ('progress', '📈 Progress Bar'), ('switch', '🔘 Toggle Switch (Boolean)'), ('status-indicator', '🟢 Status Indicator'), ('chart', '📉 Mini Chart')], default='numeric', help_text='How to display this node in the UI', max_length=20),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='icon',
            field=models.CharField(blank=True, choices=[('zap', '⚡ Power'), ('droplet', '💧 Flow/Liquid'), ('gauge', '📏 Pressure/Level'), ('thermometer', '🌡️ Temperature'), ('battery', '🔋 Battery'), ('wind', '💨 Air Flow'), ('settings', '⚙️ Status'), ('alert', '⚠️ Alert'), ('check-circle', '✓ Operational'), ('x-circle', '✗ Fault')], default='', help_text='Icon category for UI grouping', max_length=20),
        ),
        migrations.AddField(
            model_name='opcuanode',
            name='is_boolean_control',
            field=models.BooleanField(default=False, help_text='Enable for boolean nodes that should be switchable (toggle controls)'),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='acknowledge_time_out',
            field=models.IntegerField(default=5000, help_text='✓ Acknowledge timeout in milliseconds. Wait time for write operations to complete. Typical: 3000-5000ms. Range: 1000-30000ms', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='connection_time_out',
            field=models.IntegerField(default=5000, help_text='🔌 Connection timeout in milliseconds. How long to wait for server to respond to connection. Local: 3000-5000ms | Remote: 10000-15000ms | Slow: 20000-30000ms. Range: 1000-30000ms', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='request_time_out',
            field=models.IntegerField(default=10000, help_text='📝 Request timeout in milliseconds. Time to wait for OPC UA server to respond to read/write requests. Typical: 5000-10000ms. Range: 1000-60000ms', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='secure_time_out',
            field=models.IntegerField(default=10000, help_text='🔒 Secure channel timeout in milliseconds. For encrypted connections only. Minimum 5000ms recommended for secure channels. Range: 5000-30000ms', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='session_time_out',
            field=models.IntegerField(default=60000, help_text='⏱️ Session timeout in milliseconds. Server keeps session alive this long with no activity. Typical: 30000-60000ms (30-60s). Increase if frequent disconnects. Range: 5000-600000ms', validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(600000)]),
        ),
        migrations.AlterField(
            model_name='opcuaclientconfig',
            name='subscription_interval',
            field=models.IntegerField(default=5000, help_text='📈 Subscription interval in milliseconds. How often to read values from OPC UA server. Fast sensors: 1000ms | General: 5000ms | Slow sensors: 30000ms. ⚠️ MUST MATCH other SCADA systems for accurate data comparison. Range: 1000-60000ms', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(60000)]),
        ),
        migrations.AlterField(
            model_name='opcuanode',
            name='last_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationdevicespecifications',
            name='station',
            field=models.OneToOneField(help_text='The station this device belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='device_specs', to='roams_opcua_mgr.opcuaclientconfig'),
        ),
        migrations.AddIndex(
            model_name='stationdevicespecifications',
            index=models.Index(fields=['station'], name='roams_opcua_station_88d006_idx'),
        ),
    ]
