# Generated by Django 5.2.7 on 2025-12-22 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text="User's phone number for SMS notifications (format: +1234567890)", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9-15 digits, optionally starting with +', regex='^\\+?1?\\d{9,15}$')])),
                ('email_notifications', models.BooleanField(default=True, help_text='User wants to receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='User wants to receive SMS notifications')),
                ('critical_alerts_only', models.BooleanField(default=False, help_text='Only receive critical level alerts (ignore warnings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
