# Generated by Django 6.0 on 2025-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer (Read-only access)'), ('technician', 'Technician (Equipment control)'), ('operator', 'Operator (Full access to equipment)'), ('admin', 'Admin (System admin)'), ('superuser', 'Superuser (Full system access)')], default='viewer', help_text="User's role in the system", max_length=20),
        ),
    ]
