# Generated by Django 6.0 on 2026-02-13 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_api', '0002_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, help_text='Last login timestamp', null=True),
        ),
        migrations.CreateModel(
            name='L2TPVPNClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name (e.g., Bombo_BH, Nakasongola)', max_length=100, unique=True)),
                ('username', models.CharField(help_text='L2TP username for authentication', max_length=50, unique=True)),
                ('password', models.CharField(help_text='Encrypted password', max_length=255)),
                ('preshared_key', models.CharField(help_text='Encrypted IPsec Pre-Shared Key (PSK)', max_length=255)),
                ('vpn_ip', models.GenericIPAddressField(help_text='Assigned VPN IP address (10.99.0.x)')),
                ('server_ip', models.GenericIPAddressField(help_text='VPN server IP address')),
                ('max_connections', models.IntegerField(default=1, help_text='Maximum concurrent connections allowed')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Certificate expiration date (1 year from creation)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='l2tp_clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'L2TP VPN Client',
                'verbose_name_plural': 'L2TP VPN Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenVPNClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name (e.g., admin_laptop, station_control)', max_length=100, unique=True)),
                ('common_name', models.CharField(help_text='OpenVPN Certificate Common Name', max_length=64, unique=True)),
                ('certificate', models.TextField(help_text='Client certificate (PEM format)')),
                ('private_key', models.TextField(help_text='Client private key (PEM format, encrypted)')),
                ('vpn_ip', models.GenericIPAddressField(help_text='Assigned VPN IP address (10.8.0.x)')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='udp', max_length=10)),
                ('port', models.IntegerField(default=1194, help_text='OpenVPN server port')),
                ('compression_enabled', models.BooleanField(default=True, help_text='Enable LZ4 compression')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Certificate expiration date (1 year from creation)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openvpn_clients_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenVPN Client',
                'verbose_name_plural': 'OpenVPN Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPNAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create Client'), ('update', 'Update Client'), ('delete', 'Delete Client'), ('revoke', 'Revoke Client'), ('download', 'Download Config'), ('activate', 'Activate Client'), ('deactivate', 'Deactivate Client')], max_length=20)),
                ('vpn_type', models.CharField(choices=[('l2tp', 'L2TP/IPsec'), ('openvpn', 'OpenVPN')], max_length=20)),
                ('client_name', models.CharField(help_text='Name of the VPN client', max_length=100)),
                ('client_id', models.IntegerField(blank=True, help_text='ID of the VPN client (if known)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vpn_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPN Audit Log',
                'verbose_name_plural': 'VPN Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='roams_api_v_timesta_11493d_idx'), models.Index(fields=['admin_user', 'timestamp'], name='roams_api_v_admin_u_e0c3c3_idx')],
            },
        ),
    ]
