# Generated by Django 6.0 on 2026-02-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roams_api', '0003_userprofile_last_login_ip_and_more'),
        ('roams_opcua_mgr', '0014_stationdevicespecifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2tpvpnclient',
            name='station',
            field=models.ForeignKey(default=1, help_text='Associated station for this VPN client', on_delete=django.db.models.deletion.PROTECT, related_name='l2tp_vpn_clients', to='roams_opcua_mgr.opcuaclientconfig'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openvpnclient',
            name='station',
            field=models.ForeignKey(default=1, help_text='Associated station for this VPN client', on_delete=django.db.models.deletion.PROTECT, related_name='openvpn_clients', to='roams_opcua_mgr.opcuaclientconfig'),
            preserve_default=False,
        ),
    ]
